---
abstract: 'Tweet from a queue of messages'
author:
  - 'Drew Stephens <drew@dinomite.net>'
build_requires:
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Twitter-Queue
requires:
  Carp: '0'
  Moose: '0'
  Net::Twitter: '4.01005'
  Try::Tiny: '0'
  YAML::Any: '0.70'
  strict: '0'
  warnings: '0'
version: '0.4'
