---
abstract: 'Tweet from a queue of messages'
author:
  - 'Drew Stephens <drew@dinomite.net>'
build_requires:
  English: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Twitter-Queue
requires:
  Carp: 0
  Moose: 0
  Net::Twitter: 3.12000
  Try::Tiny: 0
  YAML::Any: 0.70
  strict: 0
  warnings: 0
version: 0.2
